let reportData=null,selectedStage='development',replayTimer=null,replayIndex=-1,toastTimer;
const $=id=>document.getElementById(id);
function element(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n}
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2600)}
function renderStages(){const nav=$('stage-nav'),pipeline=$('pipeline');nav.replaceChildren();pipeline.replaceChildren();reportData.stages.forEach((s,i)=>{const active=selectedStage===s.id;const n=element('button',undefined,`nav-item${active?' active':''}`);n.append(element('span',s.number,'nav-number'),element('span',s.name),element('span',s.status==='complete'?'✓':s.status==='sealed'?'Ⅱ':'—','nav-check'));n.setAttribute('aria-current',active?'step':'false');n.onclick=()=>selectStage(s.id);nav.append(n);const p=element('button',undefined,`pipeline-step ${s.status}${active?' selected':''}${replayIndex>=0&&i>replayIndex?' replay-future':''}`);p.setAttribute('aria-label',`${s.name}，${s.label}`);p.append(element('span',s.status==='complete'?'✓':s.number,'step-circle'),element('span',s.name,'step-name'),element('span',s.label,'step-label'));p.onclick=()=>selectStage(s.id);pipeline.append(p)});const s=reportData.stages.find(s=>s.id===selectedStage);$('stage-detail').replaceChildren(element('span',`STAGE ${s.number} / 07`,'detail-number'),element('h2',s.name,'detail-title'),element('span',s.label,'detail-status'),element('p',s.detail))}
function selectStage(id){selectedStage=id;renderStages();if(id==='ci')selectTab('ci');else if(id==='scan'||id==='protection')selectTab('evidence');else selectTab('overview')}
function selectTab(id){for(const b of document.querySelectorAll('.tab')){const active=b.dataset.tab===id;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))}for(const p of document.querySelectorAll('.tab-panel'))p.hidden=p.id!==id}
function renderComparison(){const rows=[['完整运行','complete','required'],['不完整记录','incomplete'],['安全违规','security_violations'],['业务失败','utility_failures']];$('comparison-rows').replaceChildren();for(const [title,key,denom] of rows){const row=element('div',undefined,'compare-row');row.append(element('span',title));for(const role of ['submitted','candidate']){const value=reportData[role][key];const bad=key!=='complete'&&value>0;const b=element('b',String(value),bad?'bad':role==='candidate'?'good':'');if(denom)b.append(element('span',`/ ${reportData[role][denom]}`));row.append(b)}$('comparison-rows').append(row)}$('pair-bar').replaceChildren();for(const key of ['improved','unchanged','regressed','unknown']){const v=reportData.paired[key];if(v){const part=element('span',undefined,`pair-part ${key}`);part.style.flex=String(v);part.title=`${key}: ${v}`;$('pair-bar').append(part)}}$('pair-note').textContent=reportData.pair_note}
function renderCI(decision){$('ci-terminal').textContent=[`profile                 orders_total`,`submitted.development   ${decision.development_submitted_verdict}`,`candidate.development   ${decision.development_candidate_verdict}`,`candidate.qualification ${decision.candidate_decision}`,`m7.protected             sealed (0 / 24)`,`github.check             not published`,`exit_code                ${decision.exit_code}`,``,`BLOCKED  ${decision.blockers.join('\nBLOCKED  ')}`].join('\n')}
function renderEvidence(){$('evidence-list').replaceChildren();const labels={candidate_bundle_digest:'候选 Bundle',config_digest:'模型 / 运行配置',source_index_digest:'运行源码快照',m6_gate_digest:'独立 M6 Gate',freeze_digest:'冻结记录',profile_acceptance_digest:'订单范围验收',spending_digest:'封存实际支出'};for(const [key,value] of Object.entries(reportData.evidence)){const b=element('button',undefined,'evidence-row');b.append(element('span',labels[key]||key),element('code',`${value.slice(0,23)}…${value.slice(-8)}  ↗`));b.setAttribute('aria-label',`复制${labels[key]}摘要`);b.onclick=async()=>{try{await navigator.clipboard.writeText(value);toast('完整摘要已复制')}catch{toast('复制不可用，请导出 JSON 报告查看')}};$('evidence-list').append(b)}const ul=element('ul');reportData.limitations.forEach(l=>ul.append(element('li',l)));$('limits').replaceChildren(ul)}
async function load(){try{const r=await fetch('/api/report');if(!r.ok)throw Error();reportData=await r.json();$('campaign-ref').textContent=reportData.campaign_id;$('updated-at').textContent=`证据快照 ${new Date(reportData.evidence_updated_at).toLocaleString('zh-CN',{hour12:false})}`;renderStages();renderComparison();renderEvidence();renderCI(reportData.local_ci);const api=reportData.api_configuration;$('api-status-text').textContent=`${api.model} · 接入校准 ${api.calibration_elapsed_seconds.toFixed(2)} 秒 · 正式运行 ${api.formal_runs} 次`;$('api-budget-detail').textContent=`费用上限 ¥${api.cost_limit_rmb}；完整新配置矩阵保守预留 ¥${api.full_66_runs_forecast_rmb.toFixed(2)}。原始 reasoning_tokens 字段缺失，正式实验待 Gate 准入。`;}catch{toast('报告不可用，请检查本地服务');$('stage-progress').textContent='报告加载失败'}}
for(const t of document.querySelectorAll('.tab'))t.onclick=()=>selectTab(t.dataset.tab);
$('show-limits').onclick=()=>{$('limits').hidden=!$('limits').hidden;$('show-limits').textContent=$('limits').hidden?'查看限制 ↗':'收起限制 ↑'};
$('refresh').onclick=async()=>{await load();toast('已重新读取封存证据快照')};
$('run-check').onclick=async()=>{const b=$('run-check');b.disabled=true;try{const r=await fetch('/api/check');if(!r.ok)throw Error();renderCI(await r.json());toast('本地判定完成 · exit code 1')}catch{toast('CI 判定暂不可用')}finally{b.disabled=false}};
function stopReplay(){clearInterval(replayTimer);replayTimer=null;replayIndex=-1;$('replay').textContent='▷ 回放流水线';$('replay-indicator').textContent='已记录结果';$('stage-progress').textContent='正式完成 4 · Demo 范围 2 · 暂缓 1';renderStages()}
$('replay').onclick=()=>{if(!reportData)return;if(replayTimer){stopReplay();return}replayIndex=0;$('replay').textContent='Ⅱ 停止回放';$('replay-indicator').textContent='证据回放 · 不启动模型';selectedStage=reportData.stages[0].id;renderStages();$('stage-progress').textContent='证据回放 1 / 7';replayTimer=setInterval(()=>{replayIndex++;if(replayIndex>=reportData.stages.length){stopReplay();toast('回放完成 · M7 封存与 CI 阻断状态保留');return}selectStage(reportData.stages[replayIndex].id);$('stage-progress').textContent=`证据回放 ${replayIndex+1} / 7`},1800)};
load();
