const $=id=>document.getElementById(id);let busy=false,key=null;
function randomKey(){return crypto.randomUUID?crypto.randomUUID():[...crypto.getRandomValues(new Uint8Array(16))].map(x=>x.toString(16).padStart(2,'0')).join('').replace(/^(.{8})(.{4})(.{4})(.{4})(.{12})$/,'$1-$2-$3-$4-$5')}
function bytes(s){return new TextEncoder().encode(s).length}
function tell(s){const n=$('notice');n.textContent=s;n.classList.add('shown');setTimeout(()=>n.classList.remove('shown'),4500)}
async function get(path){const r=await fetch(path,{cache:'no-store'}),v=await r.json();if(!r.ok)throw Error(v.error_code||'读取失败');return v}
async function recent(){try{const {submissions}=await get('/api/submissions');$('submission-count').textContent=submissions.length;const box=$('recent-list');box.replaceChildren();for(const item of submissions){const row=document.createElement('div');row.className='saved-row';row.textContent=`${item.id.slice(0,23)}… · ${item.skill_bytes} 字节 · 已保存、未运行`;box.append(row)}}catch(e){tell(e.message)}}
$('custom-file').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>8192)throw Error('文件超过 8 KiB');const content=new TextDecoder('utf-8',{fatal:true}).decode(await f.arrayBuffer());if(content.includes('\0')||bytes(content)<20)throw Error('请上传至少 20 字节的 UTF-8 Markdown');$('skill').value=content;$('file-name').textContent=`已在浏览器载入 ${f.name} · ${f.size} 字节`;tell('文件已载入；尚未提交')}catch(error){tell(error.message)}finally{e.target.value=''}};
$('run').onclick=async()=>{if(busy)return;const input={skill:$('skill').value,task:$('task').value,expected:$('expected').value,forbidden:$('forbidden').value};if(!(bytes(input.skill)>=20&&bytes(input.skill)<=8192&&bytes(input.task)>=5&&bytes(input.task)<=1000&&bytes(input.expected)>=1&&bytes(input.expected)<=256&&bytes(input.forbidden)>=3&&bytes(input.forbidden)<=100)){tell('请检查四个字段的字节长度');return}busy=true;$('run').disabled=true;try{key=key||randomKey();const r=await fetch('/api/submissions',{method:'POST',headers:{'Content-Type':'application/json','X-SkillLoop-Request':'1'},body:JSON.stringify({...input,request_key:key})}),v=await r.json();if(!r.ok)throw Error(v.error_code||'保存失败');key=null;$('status').textContent='已保存 · 实验暂停';$('saved-id').textContent=`${v.id} · ${v.skill_bytes} 字节 · ${v.skill_digest}`;tell('Skill 已保存到 DGX 私有目录，没有调用模型');await recent()}catch(e){tell(e.message)}finally{busy=false;$('run').disabled=false}};
recent();
