const $=id=>document.getElementById(id);let catalog=null,selection=new URLSearchParams(location.search).get('skill')||'orders_total',loading=false,timer;
const states={demo_ready:'闭环已交付',blocked_pre_matrix:'历史证据已收录',running:'历史证据已收录',complete:'已完成',unknown:'证据已收录',paused:'证据已收录',paused_by_user:'证据已收录',calibrating:'历史证据已收录'};
const gates={ready_with_limits:'订单范围通过 · 有限制',rejected:'未通过',pass:'通过',pending:'待复核',unknown:'未知'};
const jobStates={complete:'执行完成',incomplete:'执行不完整',running:'执行中',queued:'排队中'};
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function date(t){return t?new Date(t*1000).toLocaleString('zh-CN',{hour12:false}):'未收到状态'}
function metrics(target,rows){target.replaceChildren();for(const [value,label] of rows){const d=node('div');d.append(node('strong',value==null?'—':String(value)),node('span',label));target.append(d)}}
function renderNav(){const nav=$('profile-nav');const focused=document.activeElement?.dataset?.profile;nav.replaceChildren();for(const p of catalog.profiles){const b=node('button',undefined,`skill-choice${p.id===selection?' selected':''}`);b.dataset.profile=p.id;b.setAttribute('aria-pressed',String(p.id===selection));b.append(node('span',`0${catalog.profiles.indexOf(p)+1}`,'skill-number'),node('strong',p.name),node('span',states[p.live.state]||p.live.state,'skill-state'),node('span','↗','skill-arrow'));b.onclick=()=>{selection=p.id;history.replaceState(null,'','/?skill='+p.id);renderNav();renderDetail()};nav.append(b);if(focused===p.id)b.focus()}}
function renderDetail(){const p=catalog.profiles.find(p=>p.id===selection)||catalog.profiles[0];selection=p.id;const s=p.live;$('profile-id').textContent=p.id;$('profile-name').textContent=p.name;$('profile-description').textContent=p.description;$('profile-state').textContent=states[s.state]||s.state;$('profile-state').className='state-label '+(s.state==='demo_ready'?'ready':'');$('current-stage').textContent=s.stage;$('evidence-time').textContent=date(s.observed_at);$('stale-note').textContent=p.source==='sealed_orders_evidence'?'已封存的证据':p.stale?'较早的观测 · 等待任务更新':'任务发布的最新观测';$('current-summary').textContent=p.id==='orders_total'?'订单候选 21/21 次开发回归完整通过；攻击、修补和回归网页闭环已交付并保留真实记录。':p.history?`已复核 ${p.history.attack_attempts} 次历史攻击尝试，其中 ${p.history.attack_successes} 次确认成功；当前 API 工作另列于实验状态。`:s.summary;
if(p.id==='orders_total'){metrics($('live-metrics'),[['21 / 21','冻结候选回归'],['7','测试案例'],['42','原 Skill + 候选尝试'],['0','原攻击确认违规']]);$('metric-scope').textContent='订单 M6 封存活动；网页 Demo 为另一独立活动，结果见下方。'}else if(p.history){const h=p.history;metrics($('live-metrics'),[[h.attack_successes,'历史确认攻击成功'],[h.attack_attempts,'历史攻击尝试'],[h.attack_complete,'完整攻击记录'],[h.attack_incomplete,'不完整攻击记录']]);$('metric-scope').textContent=`历史活动 ${h.activity_id} · 不与当前 API 实验合并。`}else{metrics($('live-metrics'),[[s.matrix_attempts,'当前矩阵尝试'],[s.complete,'完整记录'],[s.incomplete,'不完整记录'],[s.security_violations,'确认安全违规']]);$('metric-scope').textContent='当前任务发布的脱敏状态。'}$('current-gate').textContent=gates[s.gate]||s.gate;$('freeze-state').textContent=s.frozen===true?'候选已冻结':s.frozen===false?'候选未冻结':'冻结状态未知';$('blockers').replaceChildren(...s.blockers.map(b=>node('li',b)));$('activity-id').textContent=s.activity_id?`当前活动 ${s.activity_id}`:'正式矩阵尚无活动身份';const actions=$('profile-actions');actions.replaceChildren();if(p.interactive_workflow){for(const [text,url,cls] of [['查看订单工作台 →','/workbench','action primary'],['查看订单历史报告','/orders','action secondary']]){const a=node('a',text,cls);a.href=url;actions.append(a)}actions.append(node('span','实验已暂停；工作台保留既有记录和 Skill 编辑。','action-note'))}else{const a=node('a','上传自己的文本 Skill →','action secondary');a.href='/custom';actions.append(a,node('p','该 Skill 的专用工具实验由独立任务推进。','action-note'))}
const j=p.latest_demo;$('demo-section').hidden=!j;if(j){$('demo-status').textContent=jobStates[j.status]||j.status;metrics($('demo-metrics'),[[`${(j.submitted?.complete||0)+(j.candidate?.complete||0)} / 6`,'完整场景运行'],[j.usage.requests,'API 请求'],[j.wall_seconds?`${j.wall_seconds.toFixed(1)} 秒`:'—','本次墙钟'],[`¥${(j.usage.cost_micro_rmb/1e6).toFixed(5)}`,'本次记录支出']]);$('demo-identity').textContent=`${j.id} · ${date(j.updated_at)}`}
const h=p.history;$('history-section').hidden=!h;if(h){$('history-id').textContent=h.activity_id;$('history-scope').textContent=h.scope;metrics($('history-metrics'),[[h.attack_attempts,'攻击实际尝试'],[h.attack_complete,'完整攻击记录'],[h.attack_incomplete,'不完整攻击记录'],[h.attack_successes,'确认攻击成功']]);$('history-note').textContent=h.note}
$('scope-note').textContent=p.id==='orders_total'?'M6 订单开发候选与本地 CI/CD、网页 Demo 已交付。M7 暂缓；正式全局验收尚未通过。':'当前 API 准入、历史攻击结果与最终验收各自独立。历史成功次数不会计入当前活动，也不表示当前候选已通过。';}
async function refresh(){if(loading)return;loading=true;clearTimeout(timer);try{const r=await fetch('/api/profiles',{cache:'no-store'});if(!r.ok)throw Error();catalog=await r.json();renderNav();renderDetail();$('sync-state').textContent='已连接 · 自动刷新';$('sync-state').className='connected';$('fetch-time').textContent=`页面读取 ${date(catalog.fetched_at)}`}catch{$('sync-state').textContent='连接失败 · 保留上次结果';$('sync-state').className='disconnected'}finally{loading=false;timer=setTimeout(refresh,5000)}}
$('refresh').onclick=refresh;document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});refresh();
