const $=id=>document.getElementById(id),stageNames={scan:'规则扫描',attack:'真实攻击',repair:'模型修补',regression:'候选回归',acceptance:'本地验收'};
let timer=null,selection=null;
function el(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n}
async function get(url){const response=await fetch(url);if(!response.ok)throw Error('报告暂不可用');return response.json()}
function metrics(target,items){target.replaceChildren();for(const [value,label] of items){const n=el('div','');n.append(el('strong',String(value)),el('span',label));target.append(n)}}
async function display(id){selection=id;clearTimeout(timer);try{const j=await get(`/api/workflow/${id}`);if(selection!==id)return;const status={complete:'Demo 执行完成',running:'真实模型执行中',queued:'活动已创建',incomplete:'不完整记录已保留'};$('showcase-status').textContent=status[j.status];$('showcase-mode').textContent=`${j.model} · enable_thinking=false · ${id}`;$('showcase-clock').textContent=j.wall_seconds?`${j.wall_seconds.toFixed(1)} 秒`:'执行中';$('showcase-stages').replaceChildren();for(const [i,s] of j.stages.entries()){const n=el('div','',`pipeline-step ${s.status}`);n.append(el('span',s.status==='complete'?'✓':String(i+1).padStart(2,'0'),'step-circle'),el('span',stageNames[s.id],'step-name'),el('span',{complete:'完成',pending:'等待',running:'执行中',incomplete:'不完整'}[s.status],'step-label'));$('showcase-stages').append(n)}metrics($('showcase-metrics'),[[`${(j.submitted?.complete||0)+(j.candidate?.complete||0)} / 6`,'本活动完整测试'],[j.usage.requests,'真实 API 请求'],[`¥${(j.usage.cost_micro_rmb/1e6).toFixed(5)}`,'本活动支出 / 保留'],[j.usage.reasoning_usage_missing,'reasoning 原始字段缺失']]);$('showcase-results').replaceChildren();for(const [label,key] of [['实际尝试 / 必需','attempts'],['完整记录','complete'],['不完整记录','incomplete'],['安全违规','security_violations'],['业务失败','utility_failures'],['Demo 判定','verdict']]){const row=el('div','','compare-row');row.append(el('span',label));for(const role of ['submitted','candidate']){const r=j[role];row.append(el('b',r?(key==='attempts'?`${r.attempts} / ${r.required}`:String(r[key])):'—'))}$('showcase-results').append(row)}
$('showcase-effect').textContent=j.submitted?.security_violations===0?'本活动未确认攻击成功，因此不能声称修补已经证明阻断攻击。':'安全违规是真实观测结果；最终结论还须结合完整分母、回归及保护 Gate。';$('showcase-patch').textContent=j.repair?`修补稿 ${j.repair.original_bytes} → ${j.repair.candidate_bytes} 字节；冻结候选摘要 ${j.repair.candidate_digest}`:'等待模型修补。';const review=await get(`/api/workflow/${id}/review`);if(selection!==id)return;$('showcase-proof').textContent=review.status==='pass'?'Demo 工作流复核通过':review.status==='pending'?'独立复核待完成':'独立复核未通过';$('showcase-proof-digest').textContent=review.digest||'';$('showcase-export').hidden=false;$('showcase-export').href=`/api/workflow/${id}/review`;$('showcase-export').download=`${id}-review.json`;if(['queued','running'].includes(j.status)||j.verification?.status==='pending')timer=setTimeout(()=>display(id),2500)}catch(error){$('showcase-status').textContent=error.message;timer=setTimeout(()=>display(id),5000)}}
async function load(){try{const [{jobs},baseline]=await Promise.all([get('/api/workflow'),get('/api/report')]);metrics($('showcase-baseline'),[[`${baseline.candidate.complete} / ${baseline.candidate.required}`,'历史候选完整回归'],[baseline.candidate.unresolved_high,'未处置 high'],[baseline.candidate.frozen?'已冻结':'未冻结','M6 订单候选'],['已通过','M8 本地 CI/CD 测试']]);const select=$('showcase-activity');select.replaceChildren();for(const j of jobs){const option=el('option',`${j.id.slice(0,17)}… · ${j.status}`);option.value=j.id;select.append(option)}select.onchange=()=>display(select.value);if(jobs.length)display(jobs[0].id);else{$('showcase-status').textContent='尚无活动，请打开工作台运行';select.disabled=true}}catch(error){$('showcase-status').textContent=error.message}}
load();
