const byId=id=>document.getElementById(id),names={scan:'规则扫描',attack:'真实攻击',repair:'模型修补',regression:'候选回归',acceptance:'本地验收'};
let activeJob=null,pollTimer=null,starting=false,requestKey=null;
function newRequestKey(){if(crypto.randomUUID)return crypto.randomUUID();const bytes=crypto.getRandomValues(new Uint8Array(16));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const hex=[...bytes].map(b=>b.toString(16).padStart(2,'0')).join('');return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`}
function node(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n}
function notice(text){byId('toast').textContent=text;byId('toast').classList.add('visible');setTimeout(()=>byId('toast').classList.remove('visible'),4000)}
async function get(url){const r=await fetch(url);const value=await r.json();if(!r.ok)throw Error(value.error_code||'服务不可用');return value}
function stages(job){const target=byId('live-stages');target.replaceChildren();for(const [i,s] of (job?.stages||Object.keys(names).map(id=>({id,status:'pending'}))).entries()){const b=node('div','',`pipeline-step ${s.status}${s.status==='running'?' selected':''}`);b.append(node('span',s.status==='complete'?'✓':String(i+1).padStart(2,'0'),'step-circle'),node('span',names[s.id],'step-name'),node('span',{pending:'等待',running:'执行中',complete:'完成',incomplete:'不完整'}[s.status],'step-label'));target.append(b)}}
function render(job){activeJob=job;stages(job);byId('job-status').textContent={queued:'排队中',running:'真实模型执行中',complete:'Demo 全流程完成',incomplete:'执行不完整 · 证据保留'}[job.status];byId('activity-id').textContent=job.id;byId('start-workflow').disabled=true;byId('skill-editor').disabled=byId('start-workflow').disabled;byId('restore-skill').disabled=byId('start-workflow').disabled;byId('skill-upload').disabled=byId('start-workflow').disabled;const rows=byId('live-results');rows.replaceChildren();for(const [label,key] of [['实际尝试 / 必需','attempts'],['完整记录','complete'],['不完整记录','incomplete'],['安全违规','security_violations'],['业务失败','utility_failures'],['Demo 判定','verdict']]){const row=node('div','','compare-row');row.append(node('span',label));for(const role of ['submitted','candidate']){const r=job[role];row.append(node('b',r?(key==='attempts'?`${r[key]} / ${r.required}`:String(r[key])):'—'))}rows.append(row)}
const patch=job.repair;byId('repair-summary').textContent=patch?`已应用并冻结本次候选：${patch.original_bytes} → ${patch.candidate_bytes} 字节，净变化 ${patch.net_growth_bytes} 字节。候选摘要 ${patch.candidate_digest}`:'等待模型修补。';const u=job.usage,usage=byId('live-usage');usage.replaceChildren();for(const [label,value] of [['API 请求',u.requests],['Prompt tokens',u.prompt_tokens],['Completion tokens',u.completion_tokens],['原始 reasoning 缺失',u.reasoning_usage_missing],['已知 reasoning tokens',u.reasoning_tokens_known],['本次支出 / 保留',`¥${(u.cost_micro_rmb/1000000).toFixed(5)}`]]){const row=node('div','');row.append(node('span',label),node('b',String(value)));usage.append(row)}
const d=job.decision;byId('live-terminal').textContent=[`activity                 ${job.id}`,`mode                     real_model_demo`,`enable_thinking          false`,`submitted.demo           ${job.submitted?.verdict||'pending'}`,`candidate.demo           ${job.candidate?.verdict||'pending'}`,`candidate.qualification  ${job.qualification}`,`original_ci_exit_code    ${d?.exit_code??'pending'}`,`formal_attestation       false`,`m7                       deferred`,...(job.qualification_blockers||[]).map(x=>`HELD                     ${x}`),...(job.error_code?[`INCOMPLETE               ${job.error_code}`]:[])].join('\n');byId('live-export').hidden=false;byId('live-export').href=`/api/workflow/${job.id}`;byId('live-export').download=`${job.id}.json`;byId('live-updated').textContent=`更新 ${new Date(job.updated_at*1000).toLocaleString('zh-CN')}`;
byId('independent-proof').textContent=job.verification?.status==='pass'?`独立 Demo 复核通过 · ${job.verification.digest}`:job.verification?.status==='held'?'独立复核未通过，证据保留。':'独立复核待完成；可在展示模式查看已封存的复核结果。';
if(['queued','running'].includes(job.status)||job.verification?.status==='pending'){clearTimeout(pollTimer);pollTimer=setTimeout(()=>refreshJob(job.id),2500)}else{clearTimeout(pollTimer);loadRecent()}}
async function refreshJob(id){try{render(await get(`/api/workflow/${id}`))}catch(e){notice(e.message);pollTimer=setTimeout(()=>refreshJob(id),5000)}}
async function loadRecent(){try{const {jobs}=await get('/api/workflow');const target=byId('recent-jobs');target.replaceChildren();for(const job of jobs){const b=node('button',`${job.id.slice(0,17)}… · ${job.status}`,'text-button recent-job');b.onclick=()=>refreshJob(job.id);target.append(b)}if(!activeJob&&jobs.length)render(jobs[0])}catch(e){notice(e.message)}}
async function restore(){try{byId('skill-editor').value=(await get('/api/workflow/default')).skill}catch(e){notice(e.message)}}
byId('restore-skill').onclick=restore;
byId('skill-upload').onchange=async event=>{const file=event.target.files?.[0];if(!file)return;try{if(file.size>8192)throw Error('Skill 文件超过 8 KiB 上限');const bytes=new Uint8Array(await file.arrayBuffer());const value=new TextDecoder('utf-8',{fatal:true}).decode(bytes);if(value.includes('\0')||bytes.length<20)throw Error('请上传 20 字节以上的 UTF-8 Markdown');byId('skill-editor').value=value;byId('upload-note').textContent=`已在本地载入 ${file.name}（${bytes.length} 字节）。检查或修改后，再点击“运行全流程”提交到受控订单 Demo。`;notice('文件已载入编辑框；尚未启动实验')}catch(error){notice(error.message)}finally{event.target.value=''}};
byId('start-workflow').onclick=()=>notice('后台实验已暂停，当前只展示历史结果');
stages();restore();loadRecent();
